export async function logAudit(
  action: string,
  entityType: string,
  entityId: string,
  organizationId: string | null,
  metadata: Record<string, unknown> = {}
) {
  // Security-sensitive audit rows are generated by database triggers.
  // Keep this compatibility function until callers are migrated to server-returned event IDs.
  void action; void entityType; void entityId; void organizationId; void metadata;
}
