import { useMemo, useState } from 'react';
import { AlertTriangle, Building2, CheckCircle2, ClipboardList, FileText, Plus, Search, Shield, Users } from 'lucide-react';

type PreviewScreen = 'dashboard' | 'organizations' | 'staff' | 'documents' | 'alerts' | 'tasks' | 'audit_logs';
type Row = { cells: React.ReactNode[]; tone?: 'urgent' | 'warning' | 'success' };

const DATA: Record<PreviewScreen, { title: string; subtitle: string; headers: string[]; rows: Row[] }> = {
  dashboard: { title: 'Clinic overview', subtitle: 'Operational summary · refreshed 4 min ago', headers: ['Clinic', 'Patients', 'Active wounds', 'Reviews due', 'Status'], rows: [
    { cells: ['Al Nakheel Wound Clinic', '142', '186', '7', 'Active'], tone: 'success' }, { cells: ['Riyadh North Community Care', '86', '103', '4', 'Active'], tone: 'success' }, { cells: ['Al Olaya Home Health', '54', '61', '2', 'Onboarding'], tone: 'warning' }] },
  organizations: { title: 'Organizations', subtitle: 'Manage clinics, hospitals, and care facilities', headers: ['Organization', 'Type', 'Location', 'Members', 'Status'], rows: [
    { cells: ['Al Nakheel Wound Clinic', 'Wound clinic', 'Riyadh', '18', 'Active'], tone: 'success' }, { cells: ['Riyadh North Community Care', 'Outpatient clinic', 'Riyadh', '11', 'Active'], tone: 'success' }, { cells: ['Al Olaya Home Health', 'Home healthcare', 'Riyadh', '7', 'Onboarding'], tone: 'warning' }, { cells: ['King Fahd Care Network', 'Hospital', 'Dammam', '24', 'Active'], tone: 'success' }] },
  staff: { title: 'Team & access', subtitle: 'Clinic membership, roles, scope and security status', headers: ['Member', 'Role', 'Scope', 'Last active', 'MFA'], rows: [
    { cells: ['Dr. Rana Nasser', 'Clinician', 'All patients', '8 min ago', 'On'], tone: 'success' }, { cells: ['Layla Al-Salem', 'Nurse', 'Assigned patients', '14 min ago', 'On'], tone: 'success' }, { cells: ['Omar Al-Qahtani', 'Clinic admin', 'Clinic', '1 h ago', 'On'], tone: 'success' }, { cells: ['Maha Al-Harbi', 'Nurse', 'Assigned patients', 'Yesterday', 'Required'], tone: 'warning' }] },
  documents: { title: 'Document library', subtitle: 'Clinical protocols, consent forms and patient education', headers: ['Document', 'Category', 'Version', 'Owner', 'Updated'], rows: [
    { cells: ['Wound photography protocol', 'Clinical protocol', 'v3.2', 'Dr. R. Nasser', 'Aug 18, 2026'] }, { cells: ['Consent for clinical imaging', 'Consent', 'v2.1', 'Compliance', 'Aug 12, 2026'] }, { cells: ['Diabetic foot self-care', 'Patient education', 'v1.8', 'Nursing team', 'Jul 29, 2026'] }, { cells: ['Escalation and referral pathway', 'Clinical protocol', 'v4.0', 'Medical director', 'Jul 17, 2026'] }] },
  alerts: { title: 'Alerts', subtitle: 'Rule-versioned clinical alerts and escalation history', headers: ['Severity', 'Alert', 'Patient', 'Notified', 'State'], rows: [
    { cells: ['Urgent', 'Area increased 16% since prior visit', 'Mohammed Al-Hassan', 'Dr. R. Nasser · SMS', 'Unacknowledged'], tone: 'urgent' }, { cells: ['Review', 'New periwound erythema recorded', 'Fatimah Al-Harbi', 'Wound team · App', 'Acknowledged'], tone: 'warning' }, { cells: ['Review', 'Check-in overdue by 52 hours', 'Sara Al-Dosari', 'Assigned nurse · App', 'Acknowledged'], tone: 'warning' }, { cells: ['Closed', 'Pain increased by 3 points', 'Noura Al-Qahtani', 'Dr. R. Nasser · Email', 'Closed'], tone: 'success' }] },
  tasks: { title: 'Tasks', subtitle: 'Clinical follow-up and operational work queue', headers: ['Priority', 'Task', 'Patient', 'Due', 'Status'], rows: [
    { cells: ['Urgent', 'Review worsening plantar ulcer', 'Mohammed Al-Hassan', 'Today, 11:30', 'In progress'], tone: 'urgent' }, { cells: ['High', 'Call patient about missed check-in', 'Sara Al-Dosari', 'Today', 'Pending'], tone: 'warning' }, { cells: ['Medium', 'Confirm dressing supply delivery', 'Fatimah Al-Harbi', 'Tomorrow', 'Pending'] }, { cells: ['Routine', 'Sign weekly assessment', 'Noura Al-Qahtani', 'Aug 22', 'Completed'], tone: 'success' }] },
  audit_logs: { title: 'Access audit', subtitle: 'Immutable record access and change history retained per clinic policy', headers: ['Time', 'Actor', 'Action', 'Target', 'Result'], rows: [
    { cells: ['10:42:16', 'Layla Al-Salem', 'Created assessment', 'MRN 728382-A · W-1', 'Allowed'], tone: 'success' }, { cells: ['10:38:04', 'Dr. Rana Nasser', 'Viewed patient record', 'MRN 529381-B', 'Allowed'], tone: 'success' }, { cells: ['10:17:51', 'Omar Al-Qahtani', 'Updated staff role', 'Maha Al-Harbi', 'Allowed'], tone: 'success' }, { cells: ['09:58:22', 'Unknown device', 'Export attempted', 'MRN 481029-C', 'Denied'], tone: 'urgent' }, { cells: ['09:42:03', 'Layla Al-Salem', 'Uploaded wound image', 'MRN 728382-A · W-1', 'Allowed'], tone: 'success' }] },
};

const icons = { dashboard: Building2, organizations: Building2, staff: Users, documents: FileText, alerts: AlertTriangle, tasks: ClipboardList, audit_logs: Shield };

export default function PreviewDataScreen({ screen }: { screen: PreviewScreen }) {
  const data = DATA[screen], Icon = icons[screen]; const [query, setQuery] = useState('');
  const rows = useMemo(() => data.rows.filter(row => !query || row.cells.join(' ').toLowerCase().includes(query.toLowerCase())), [data.rows, query]);
  const stats = screen === 'dashboard' ? [['Active patients','282'],['Active wounds','350'],['Needs review','13'],['Improving','214']] : null;
  return <div className="wt-screen"><div className="wt-page-head"><div><h1>{data.title}</h1><p>{data.subtitle}</p></div>{['organizations','staff','documents','tasks'].includes(screen)&&<button className="wt-button primary"><Plus size={15}/> Add {screen==='staff'?'member':screen==='documents'?'document':screen==='tasks'?'task':'organization'}</button>}</div>
    <div className="wt-notice"><b>Preview mode</b> Representative clinic data is shown until Supabase is connected.</div>
    {stats&&<div className="wt-kpis">{stats.map((item,index)=><article key={item[0]} className={index===2?'warning':index===3?'success':''}><p>{item[0]}</p><strong>{item[1]}</strong><span>{index===2?'4 due today':index===3?'61% of active wounds':'across 4 facilities'}</span></article>)}</div>}
    <div className="flex items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2 text-xs text-stone-500"><Icon size={16} className="text-[#1f6f6b]"/>{rows.length} records</div><label className="wt-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${data.title.toLowerCase()}`}/></label></div>
    <div className="preview-table-wrap bg-[#fffefc] border border-stone-200 rounded-xl overflow-auto"><table className="preview-table w-full min-w-[760px] text-left"><thead><tr className="bg-[#faf8f5] border-b border-stone-200">{data.headers.map(header=><th key={header} className="px-4 py-3 text-[10.5px] uppercase tracking-wide text-stone-400 font-semibold">{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-b last:border-0 border-stone-100 hover:bg-[#faf8f5]">{row.cells.map((cell,cellIndex)=><td key={cellIndex} data-label={data.headers[cellIndex]} className={`px-4 py-3.5 text-xs ${cellIndex===0?'font-semibold text-stone-900':'text-stone-600'}`}>{cellIndex===row.cells.length-1?<span className={`wt-pill ${row.tone==='urgent'?'urgent':row.tone==='warning'?'review':row.tone==='success'?'improving':'stable'}`}>{cell}</span>:cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="wt-empty">No preview records match your search.</div>}</div>
    {screen==='alerts'&&<div className="mt-4 text-xs text-stone-500 flex gap-2 items-center"><CheckCircle2 size={15} className="text-emerald-600"/>Every alert retains its rule version, trigger values, notifications and closure.</div>}
  </div>;
}
